# Generated by Django 2.2 on 2019-10-26 22:00

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('published_date', models.DateField()),
                ('industry_identifies', picklefield.fields.PickledObjectField(editable=False)),
                ('page_count', models.IntegerField()),
                ('image_links', picklefield.fields.PickledObjectField(editable=False)),
                ('language', models.CharField(max_length=3)),
                ('authors', models.ManyToManyField(to='book.Author')),
            ],
        ),
    ]
